package com.nqobza.wetutors

// Parent Users class
open class Users(
    val name: String,
    val surname: String,
    val email: String,
    val uid: String
)

// Tutor class with proper constructor
class Tutor(
    name: String,
    surname: String,
    email: String,
    uid: String,   // UID should come from Firebase, not the phone number
    val phoneNumber: String
) : Users(name, surname, email, uid)

// Student class with proper constructor
class Student(
    name: String,
    surname: String,
    email: String,
    uid: String,   // UID is still properly generated by Firebase
    val school: String
) : Users(name, surname, email, uid)

